version: '3.7'

x-logging:
  &default-logging
  options:
    max-size: '1m'
    max-file: '1'
  driver: json-file

services:
  app:
    container_name: node
    build: 
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
      - expo_cache:/app/.expo
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.101
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_DEBUG=true
      - CHOKIDAR_USEPOLLING=true
    logging: *default-logging
    tty: true
    command: ['bash', '-c', 'rm -rf /app/.expo/* && expo start']

volumes:
  node_modules:
    driver: local
  expo_cache:
    driver: local
